/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void speedLimitSliderChanged(GSlider source, GEvent event) { //_CODE_:speedLimitSlider:930268:
  
} //_CODE_:speedLimitSlider:930268:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:758401:
  paused = !paused;
} //_CODE_:pauseButton:758401:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("DriveBy");
  speedLimitSlider = new GSlider(this, 190, 0, 100, 40, 10.0);
  speedLimitSlider.setLimits(80.0, 60.0, 120.0);
  speedLimitSlider.setNumberFormat(G4P.DECIMAL, 2);
  speedLimitSlider.setOpaque(false);
  speedLimitSlider.addEventHandler(this, "speedLimitSliderChanged");
  label1 = new GLabel(this, 100, 10, 90, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Speed Limit");
  label1.setTextBold();
  label1.setOpaque(false);
  pauseButton = new GButton(this, 10, 10, 80, 30);
  pauseButton.setText("Pause");
  pauseButton.setTextBold();
  pauseButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  pauseButton.addEventHandler(this, "pauseButtonClicked");
}

// Variable declarations 
// autogenerated do not edit
GSlider speedLimitSlider; 
GLabel label1; 
GButton pauseButton; 
